export const CATEGORIES = [
  { id: "warmup", label: "Warm-up" },
  { id: "groundballs", label: "Ground balls" },
  { id: "passing", label: "Passing" },
  { id: "shooting", label: "Shooting" },
  { id: "dodging", label: "Dodging" },
  { id: "games", label: "Small games" },
  { id: "together", label: "Full group" },
];

export const DRILL_BANK = [
  {
    id: "warmup",
    name: "Dynamic Warm-Up",
    short: "Warm-Up",
    category: "warmup",
    station: false,
    diagram: "warmup",
    setup: ["15-yard strip of field", "Sticks in hand", "Full roster together"],
    how: [
      "High knees & butt kicks — 2 min, across 15 yards.",
      "Side shuffles & carioca — 2 min, facing sideways.",
      "Walking lunges with a twist — 2 min.",
      "Leg swings & inchworms — 2 min. Use sticks for balance.",
      "Arm circles & cradle motion — 2 min. Stick overhead.",
    ],
    focus: ["Heart rate up", "Hips, shoulders, wrists", "Cradle the stick from the first minute"],
    say: "Sticks in the box. Move together. We cradle from the first minute.",
  },
  {
    id: "scoop",
    name: "3-Cone Scoop & Accelerate",
    short: "3-Cone Scoop",
    category: "groundballs",
    station: true,
    diagram: "scoop",
    setup: ["3 parallel lines, 3–4 girls each", "3 cones per line, 5 yards apart", "Coach with a pile of balls at the start"],
    how: [
      "Coach rolls a ground ball past the second cone.",
      "Girl sprints, gets low (two butts down), scoops on the run — do not stop.",
      "Cradle through the cones, switching hands.",
      "Come back around the last cone and pass to the teammate who just finished (she goes to the end of the line after the catch).",
    ],
    focus: ["Run through the ball", "Protected cradle right after the scoop", "Switch hands"],
    say: "Two butts down. Scoop on the run. Do not stop.",
  },
  {
    id: "ones-gb",
    name: "1v1 Ground Balls",
    short: "1v1 GB",
    category: "groundballs",
    station: true,
    diagram: "scramble",
    setup: ["Two lines side-by-side, 5 yards behind the coach", "Open space in front for the 1v1"],
    how: [
      "Coach rolls a loose ball between the lines and yells Go.",
      "Both girls sprint. Winner boxes out, scoops, and protects.",
      "Then either score on goal or pass back to the coach while the other girl applies light pressure.",
    ],
    focus: ["Boxing out", "Body position", "Clear space under pressure"],
    say: "Win the body first. Box out. Scoop. Protect.",
  },
  {
    id: "hippos",
    name: "Hungry Hippos",
    short: "Hippos",
    category: "groundballs",
    station: true,
    diagram: "hippos",
    setup: ["Lots of balls scattered in a box", "Two teams, each with a bucket or small goal", "3–4 girls go at a time if the group is big"],
    how: [
      "Whistle: girls sprint, scoop one ball, cradle back, and drop it in their bucket.",
      "No raking. Scoop through and protect.",
      "When the balls are gone, the team with more in the bucket wins.",
    ],
    focus: ["Scoop on the run", "Eyes up to the bucket", "Compete, then reset fast"],
    say: "One ball. Scoop through. Get it in YOUR bucket.",
  },
  {
    id: "musical-gb",
    name: "Musical Ground Balls",
    short: "Musical GB",
    category: "groundballs",
    station: true,
    diagram: "scramble",
    setup: ["Girls face the coach", "One fewer ball than girls, scattered behind them"],
    how: [
      "Whistle: they turn, sprint, and scoop. Girl without a ball is out.",
      "Pull one ball each round until you have a winner.",
      "Praise the girls who get low and run through the ball.",
    ],
    focus: ["First step", "Two butts down", "Find a ball, don’t watch teammates"],
    say: "Turn. Sprint. Scoop. There’s one missing — go get yours.",
  },
  {
    id: "man-ball",
    name: "2v1 Ground Balls",
    short: "2v1 GB",
    category: "groundballs",
    station: true,
    diagram: "fastbreak",
    setup: ["Two girls on offense, one on defense", "Coach rolls the loose ball"],
    how: [
      "Offense must win the ground ball and complete one pass before they can go to goal or pass back to the coach.",
      "Defense: play the ball-girl. Do not hover in the middle.",
      "Rotate the defender each rep.",
    ],
    focus: ["Man / ball", "Outlet pass after the scoop", "Support the girl who won it"],
    say: "Win it. One pass. Don’t stand and admire the scoop.",
  },
  {
    id: "relay",
    name: "Ground Ball Relay",
    short: "Relay",
    category: "groundballs",
    station: false,
    diagram: "relay",
    setup: ["4 even teams", "Weave cone course in front of each line", "One ball per team"],
    how: [
      "Race: scoop, cradle through the weave, pass back to the next girl in front of the line.",
      "Next girl goes. First team finished wins.",
    ],
    focus: ["Scoop on the run", "Cradle through traffic", "Clean pass to the next teammate"],
    say: "Race. Scoop, weave, pass. First team done wins.",
  },
  {
    id: "give-go",
    name: "Give-and-Go Drive to Net",
    short: "Give & Go",
    category: "shooting",
    station: true,
    diagram: "giveGo",
    setup: ["Coach at the top of the 8-meter fan with a bucket of balls", "Line of girls 15 yards out on the wing", "Goalie or empty net"],
    how: [
      "Girl passes to the coach, then cuts toward the goal.",
      "Coach hits her in stride on the return pass.",
      "She shoots on goal.",
    ],
    focus: ["Catch in stride", "Sharp cut, change of direction", "Throw ahead of the cutter"],
    say: "Pass, cut hard, catch in stride, shoot.",
  },
  {
    id: "catch-shoot",
    name: "Catch and Shoot",
    short: "Catch & Shoot",
    category: "shooting",
    station: true,
    diagram: "shot",
    setup: ["Feeder (coach) with a pile of balls", "Line 12–15 yards out, slightly off the hash", "Goal"],
    how: [
      "Girl cuts to a shooting spot, stick in the box, feet set before the ball arrives.",
      "Catch and shoot immediately — no extra cradle.",
      "Rebound or clear, next girl goes. Switch sides halfway.",
    ],
    focus: ["Feet set before the catch", "Hands soft, then a quick release", "Follow through to the far post"],
    say: "Cut. Stick up. Catch. Shoot. No extra cradle.",
  },
  {
    id: "bucket-shot",
    name: "Bucket Shooting",
    short: "Bucket Shot",
    category: "shooting",
    station: true,
    diagram: "shot",
    setup: ["Bucket or cone 5–6 yards in front of the crease", "Two lines on GLE with a pile of balls each"],
    how: [
      "Girl scoops or flips a ball, runs around the bucket, and shoots.",
      "Keep the stick in the box around the turn.",
      "Left line, then right line. High reps.",
    ],
    focus: ["Protect the stick around the bucket", "Plant and shoot", "Next girl moving before the shot lands"],
    say: "Around the bucket. Stick in the box. Shoot.",
  },
  {
    id: "mine-shot",
    name: "Mine! Ground Ball to Shot",
    short: "Mine!",
    category: "shooting",
    station: true,
    diagram: "shot",
    setup: ["Girls spread on the 8-meter", "Coach/feeder on GLE with balls"],
    how: [
      "Coach rolls a ground ball into space — not to a specific girl.",
      "Someone calls Mine, scoops, and shoots.",
      "If they bobble or miss, they’re out. Last girl on the 8-meter wins.",
    ],
    focus: ["Call Mine", "Scoop through, then shoot", "Don’t ball-watch"],
    say: "Call it. Scoop. Shoot. If you bobble, you’re out.",
  },
  {
    id: "partner-pass",
    name: "Partner Passing on the Move",
    short: "Move Pass",
    category: "passing",
    station: true,
    diagram: "passing",
    setup: ["Partners 8–10 yards apart", "One ball per pair", "A 20-yard lane to move in"],
    how: [
      "Start stationary: stick in the box, catch like an egg, pass to the opposite shoulder.",
      "Then walk, then jog, switching hands so the stick stays on the outside.",
      "Finish with a 30-second ‘how many clean catches’ contest.",
    ],
    focus: ["Target at the ear, not the hip", "Give with the catch", "Move their feet to the ball"],
    say: "Stick in the box. Hit her in stride. Soft hands.",
  },
  {
    id: "triangle-pass",
    name: "Triangle Passing",
    short: "Triangle",
    category: "passing",
    station: true,
    diagram: "triangle",
    setup: ["Groups of 3 in a triangle, 8 yards apart", "One ball per group"],
    how: [
      "Pass around the triangle. After you pass, take two steps toward the girl you threw to.",
      "Switch directions on the coach’s whistle.",
      "Progression: one bounce pass, then a catch on the run.",
    ],
    focus: ["Move after the pass", "See the next girl early", "Keep the stick up"],
    say: "Pass and move. Don’t stand and watch it.",
  },
  {
    id: "roll-dodge",
    name: "Roll Dodge to Shot",
    short: "Roll Dodge",
    category: "dodging",
    station: true,
    diagram: "dodge",
    setup: ["Cone or a coach as a dummy defender", "Line 12 yards out", "Goal"],
    how: [
      "Approach, protect the stick, roll dodge, get the stick back to the box, shoot.",
      "5 reps each side (roll away from pressure).",
      "If they have it, add a light close-out from a teammate.",
    ],
    focus: ["Protect first", "Explode out of the roll", "Stick back in the box before the shot"],
    say: "Protect. Roll. Stick back in the box. Shoot.",
  },
  {
    id: "split-dodge",
    name: "Split Dodge Lines",
    short: "Split Dodge",
    category: "dodging",
    station: true,
    diagram: "dodge",
    setup: ["Cone as the defender", "Line with balls", "Open space or a goal"],
    how: [
      "Drive at the cone, split-dodge (hands switch, stick stays in the box), accelerate past.",
      "Finish with a pass back to the line or a shot.",
      "Switch the dodge direction halfway.",
    ],
    focus: ["Change of direction", "Hands switch, head stays up", "First three steps after the dodge"],
    say: "Sell it. Switch hands. Accelerate.",
  },
  {
    id: "cradle-protect",
    name: "Stick in the Box Protect",
    short: "Protect",
    category: "dodging",
    station: true,
    diagram: "sharks",
    setup: ["Small box of cones", "Partners: one with a ball, one shadowing"],
    how: [
      "Ball-girl cradles in the box, stick by the ear, body between stick and shadow.",
      "Shadow plays light pressure — no wild checks. 20 seconds, then switch.",
      "If the ball drops, they scoop and keep going.",
    ],
    focus: ["Stick in the box", "Hips between the stick and pressure", "Keep the feet moving"],
    say: "Stick by your ear. Body in front. Don’t hide it at your hip.",
  },
  {
    id: "fastbreak",
    name: "2v1 Fast Break",
    short: "2v1",
    category: "games",
    station: true,
    diagram: "fastbreak",
    setup: ["Two attackers, one defender", "Coach throws the entry pass"],
    how: [
      "Coach feeds the offense. Offense must make one pass.",
      "Tell the defender: play the girl with the ball. Do not hover in the middle of both.",
      "The girl who shoots then stays on as defense. The others rotate.",
    ],
    focus: ["Draw the defender", "Quick decision", "Off-ball spacing"],
    say: "One pass. Draw the defender. Do not hover in the middle.",
  },
  {
    id: "west-genny",
    name: "West Genny 3v2",
    short: "3v2",
    category: "games",
    station: false,
    diagram: "westGenny",
    setup: ["2 teams", "3 lines on each side at GLE (goal line extended)", "Whole field"],
    how: [
      "Offense sends 3. Defense sends 2.",
      "Two passes must be made.",
      "Last girl to touch the ball is out. The other two offense become defense.",
      "Old defense goes to the back of the lines. 3 new girls come out on offense.",
    ],
    focus: ["Defense get back in the hole", "Offensive fast break", "Keep it moving"],
    say: "Three vs two. Two passes. Shooter is out. Defense get back in the hole.",
  },
  {
    id: "sharks",
    name: "Sharks & Minnows",
    short: "Sharks",
    category: "games",
    station: false,
    diagram: "sharks",
    setup: ["A 20×15 yard channel with two safe ends", "Every minnow has a ball", "1–2 sharks in the middle (start with a coach)"],
    how: [
      "Minnows cradle across the shark zone without dropping.",
      "Sharks play the stick head only — no body checks. 3rd/4th: keep it a bump and a poke.",
      "Drop it and you become a shark. Last minnow wins.",
    ],
    focus: ["Protected cradle", "Change of speed", "Eyes up, not at the ball"],
    say: "Protect it. Change speed. If you drop it, you’re a shark.",
  },
  {
    id: "three-v-three",
    name: "3v3 Get to a Cone",
    short: "3v3 Cones",
    category: "games",
    station: false,
    diagram: "westGenny",
    setup: ["Four cones around the 8-meter", "3v3", "Coach with a ball"],
    how: [
      "Coach rolls a ground ball. Team that wins it is on offense.",
      "All three attackers must touch a cone before they can go to goal. Defense marks up.",
      "Whistle: play. Reset after a shot or a save.",
    ],
    focus: ["Spacing", "Mark up", "No bunching in the middle"],
    say: "Win the ground ball. Get to a cone. Then go.",
  },
  {
    id: "huddle",
    name: "Huddle & Send-Off",
    short: "Huddle",
    category: "together",
    station: false,
    diagram: "huddle",
    setup: ["Full group at midfield", "Knees or sticks in"],
    how: [
      "One cue from today they did well. One thing for next practice.",
      "Water, gear, parents.",
      "Break on Dragons.",
    ],
    focus: ["Leave on a high", "One teaching point", "See you next time"],
    say: "Great work. One thing we keep, one thing we fix next time.",
  },
];

const BY_ID = Object.fromEntries(DRILL_BANK.map((d) => [d.id, d]));

export function drillById(id) {
  return BY_ID[id] ?? null;
}

export function stationDrills() {
  return DRILL_BANK.filter((d) => d.station);
}

export function togetherDrills() {
  return DRILL_BANK.filter((d) => !d.station);
}

export function drillsInCategory(category) {
  if (!category || category === "all") return DRILL_BANK;
  return DRILL_BANK.filter((d) => d.category === category);
}
